services:
  - type: web
    name: anythingllm-app
    env: node
    plan: free
    buildCommand: yarn render:build
    startCommand: yarn render:start
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: anythingllm-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true

databases:
  - name: anythingllm-db
    databaseName: anythingllm
    user: anythingllm